c	$Id: lobwth.f,v 1.1 2001/12/21 18:39:07 lombard Exp $
      COMPLEX FUNCTION LOBWTH(W,W0)
C
C $$$$$ CALLS ONLY LIBRARY ROUTINES $$$$$
C
C   LOBWTH RETURNS THE COMPLEX FORWARD TRANSFER FUNCTION OF A SIX POLE
C   BUTTERWORTH FILTER AS A FUNCTION OF ANGULAR FREQUENCY W.  THIS
C   FILTER IS A LOW PASS WITH A CORNER AT W0 AND A ROLLOFF OF ABOUT
C   36 DB/OCTAVE.  A FOURIER TRANSFORM CONVENTION OF
C   F(W) = INT F(T)*EXP(-IWT)*DT IS ASSUMED.
C
C                                                     -ALL
      COMPLEX S
      DATA A1,A2,A3/3.863703305,7.464101615,9.141620173/
      S=CMPLX(0.,W/W0)
      S=S*(A1+S*(A2+S*(A3+S*(A2+S*(A1+S)))))+1
      LOBWTH=1./S
      RETURN
      END
